---
- name: Install required packages for SonarQube installation (Debian/Ubuntu)
  ansible.builtin.apt:
    name: unzip
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install required packages for SonarQube installation (CentOS/RedHat)
  ansible.builtin.yum:
    name: unzip
    state: present
  when: ansible_os_family == "RedHat"

- name: Add SonarQube Group
  group:
    name: "{{ sonarqube_group }}"

- name: Add SonarQube User
  user:
    name: "{{ sonarqube_user }}"
    group: "{{ sonarqube_group }}"
    shell: /bin/bash
    home: "{{ sonarqube_install_dir }}"
    create_home: no
